name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            script: |
              pwd
              whoami

              cd /var/www/sistem-informasi-sekolah

              pwd

              git status
              git branch
              git remote -v

              git fetch origin
              git reset --hard origin/main

              git log --oneline -3

              php artisan optimize:clear

              sudo systemctl restart php8.2-fpm
