name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/sistem-informasi-sekolah

            echo "===== BEFORE ====="
            pwd
            git rev-parse HEAD
            git status

            git fetch origin

            echo "===== ORIGIN ====="
            git rev-parse origin/main

            git reset --hard origin/main

            echo "===== AFTER ====="
            git rev-parse HEAD

            php artisan optimize:clear

            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            systemctl restart php8.2-fpm
